# Generated by Django 5.2 on 2025-09-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0014_company_certificate_image_company_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PetShop.promocode'),
        ),
    ]
