# Generated by Django 5.2 on 2025-09-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0019_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banners/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
