# Generated by Django 5.2 on 2025-05-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0002_remove_customuser_role_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
