# Generated by Django 5.2 on 2025-05-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0004_delete_news_alter_faq_addition_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')]),
        ),
    ]
