# Generated by Django 5.2 on 2025-05-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0005_review_title_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', to='PetShop.supplier'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
