# Generated by Django 5.2 on 2025-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0013_promocode_discount_alter_partner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/certificates/'),
        ),
        migrations.AddField(
            model_name='company',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='Pet Shop', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='requisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
