# Generated by Django 5.2 on 2025-09-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0015_cart_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
