# Generated by Django 5.2 on 2025-05-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
