# Generated by Django 5.2 on 2025-05-14 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0006_alter_product_suppliers_alter_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularcustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=float, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=str, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PetShop.supplier'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='addition_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PetShop.producttype'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='RegularCustomer',
        ),
    ]
