# Generated by Django 5.2 on 2025-07-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='carts', through='PetShop.CartItem', to='PetShop.product'),
        ),
    ]
