# Generated by Django 5.2 on 2025-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0012_partner_alter_cart_user_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
